### ISSUE TITLE
List certificates in a path

### ISSUE THREAD

**Issue by felipevolpone** [felipevolpone/freeipa-health-checker#3]
As an administrator (of a FreeIPA environment), I want to see all certificates in a provided path.

Acceptance Criteria:
* The tool shows the certificates (and its trust flags) present in the provided path

**Comment by tomaskrizek** [comment]
Is this just an alias to `certutil -L -d $DIR` or does it offer any extra functionality?

**Comment by felipevolpone** [comment]
Is just an alias. This was the first developed feature on the project. The CLI is not useful, but the code itself is called by other methods.
