### ISSUE TITLE
Update README with up-to-date commands

### ISSUE THREAD

**Issue by tomaskrizek** [felipevolpone/freeipa-health-checker#8]
This is a minor documentation issue, but could you please upgrade the README file to have up-to-date commands the user can just copy-paste to use?

1. https instead of ssh for git + update name to `freeipa-health-checker`
```
git clone https://github.com/felipevolpone/freeipa-health-checker.git
cd freeipa-health-checker
```

2. update tool's name in usage commands to `freeipa_health_checker`
```
python -m freeipa_health_checker.checker -h
```

**Comment by felipevolpone** [comment]
Done in 01b869fc779f57f46717566293d7bac1195e0b92
